-- Kalimat / كلمات — initial Supabase schema
-- Run in Supabase SQL editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'لاعب',
  avatar text not null default '🧠',
  role text not null default 'player' check (role in ('player','editor','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.player_states (
  user_id uuid primary key references auth.users(id) on delete cascade,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id text primary key,
  label_ar text not null,
  icon text,
  created_at timestamptz not null default now()
);

create table if not exists public.content_entries (
  id uuid primary key default gen_random_uuid(),
  canonical_answer text not null,
  grid_answer text not null,
  normalized_key text not null,
  aliases text[] not null default '{}',
  clue text not null,
  alternate_clues text[] not null default '{}',
  category_id text references public.categories(id),
  subcategory text,
  difficulty smallint not null default 3 check (difficulty between 1 and 10),
  media_type text not null default 'text',
  media_url text,
  fact_after_solve text,
  source_url text,
  source_title text,
  source_type text,
  license text,
  license_url text,
  attribution text,
  verification_status text not null default 'candidate'
    check (verification_status in ('candidate','review','approved','rejected','archived')),
  verified_by uuid references auth.users(id),
  verified_at timestamptz,
  time_sensitive boolean not null default false,
  reverify_after timestamptz,
  tags text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.units (
  id bigint generated by default as identity primary key,
  title_ar text not null,
  subtitle_ar text,
  sequence_no integer not null unique,
  status text not null default 'draft' check (status in ('draft','review','published','archived')),
  difficulty_floor numeric(4,2),
  difficulty_ceiling numeric(4,2),
  grid jsonb,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.unit_entries (
  unit_id bigint not null references public.units(id) on delete cascade,
  entry_id uuid not null references public.content_entries(id) on delete restrict,
  clue_number integer,
  direction text check (direction in ('H','V')),
  row_no integer,
  col_no integer,
  answer_order integer,
  primary key (unit_id, entry_id)
);

create table if not exists public.editorial_reviews (
  id bigint generated always as identity primary key,
  entry_id uuid not null references public.content_entries(id) on delete cascade,
  reviewer_id uuid references auth.users(id),
  decision text not null check (decision in ('approve','reject','changes')),
  notes text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.player_states enable row level security;
alter table public.categories enable row level security;
alter table public.content_entries enable row level security;
alter table public.units enable row level security;
alter table public.unit_entries enable row level security;
alter table public.editorial_reviews enable row level security;

drop policy if exists "profiles own read" on public.profiles;
create policy "profiles own read" on public.profiles
for select using (auth.uid() = id);

drop policy if exists "profiles own update" on public.profiles;
create policy "profiles own update" on public.profiles
for update using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "player state own read" on public.player_states;
create policy "player state own read" on public.player_states
for select using (auth.uid() = user_id);

drop policy if exists "player state own insert" on public.player_states;
create policy "player state own insert" on public.player_states
for insert with check (auth.uid() = user_id);

drop policy if exists "player state own update" on public.player_states;
create policy "player state own update" on public.player_states
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "published categories readable" on public.categories;
create policy "published categories readable" on public.categories
for select using (true);

drop policy if exists "approved content readable" on public.content_entries;
create policy "approved content readable" on public.content_entries
for select using (verification_status = 'approved');

drop policy if exists "published units readable" on public.units;
create policy "published units readable" on public.units
for select using (status = 'published');

drop policy if exists "published unit entries readable" on public.unit_entries;
create policy "published unit entries readable" on public.unit_entries
for select using (
  exists (
    select 1 from public.units u
    where u.id = unit_entries.unit_id and u.status = 'published'
  )
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email,'@',1), 'لاعب'))
  on conflict (id) do nothing;
  insert into public.player_states (user_id, state)
  values (new.id, '{}'::jsonb)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

insert into public.categories (id,label_ar,icon) values
('science','العلوم والطبيعة','🔬'),
('geography','العالم والجغرافيا','🌍'),
('history','التاريخ والحضارات','🏺'),
('islam','الإسلام والحضارة','☪️'),
('literature','الأدب والشعر','📚'),
('sayings','اللغة والأمثال','🗣️'),
('sports','الرياضة','⚽'),
('food','مطابخ العالم','🍲'),
('animals','الحيوانات والنباتات','🐘'),
('tech','التقنية والاختراعات','💻'),
('arts','الفن والسينما','🎨'),
('general','ثقافة عامة','🧠')
on conflict (id) do update set label_ar=excluded.label_ar, icon=excluded.icon;
